#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file in a custom format
while read -r line; do
  while IFS=':' read -r -a arr; do
    USERNAME=${arr[0]}
    GROUP_ID=${arr[3]}
    HOME_DIRECTORY=${arr[5]}
    COMMAND_SHELL=${arr[6]}
    USER_ID=${arr[2]}
    PASSWORD=${arr[1]}
    USER_ID_INFO=${arr[4]}
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
  done <<< "$line"
done < /etc/passwd
